### ISSUE TITLE
Call for HD-CBPS

### ISSUE THREAD

**Issue by Chris-Aitken** [kosukeimai/CBPS#17]
Hi there! Firstly, thank you for producing and maintaining this package! It's an excellent resource.

I'm currently conducting some research and would like to make use of your implementation of the **HD-CBPS** estimator. However, I'm having difficult with the function, and I suspect that it's just my interpretation of the documentation that is to blame. Could you please clarify the structure of the formula to be passed and the input type for the `y` argument?

For the latter, I get `Error in which(coef(cov1) != 0) : argument to 'which' is not logical` when I pass data directly, but when I simply reference the variable name (which is contained within the `data.frame` passed to `data`), it fails to recognise it (i.e.,  it returns `object 'foo' not found`).

**Comment by psdsam** [comment]
Hi Chris,

Thank you for your interest and using our package. This is a known issue
and it is due to the R version we are using. A quick fix would be to change
the 18 and 19 lines in the function hdCBPS.fit from

  S1 = which(coef(cov1)!=0)
  S0 = which(coef(cov0)!=0)

to

  S1 = which(as.logical(coef(cov1)!=0))
  S0 = which(as.logical(coef(cov0)!=0))

We are working on improving the HD method and a new version will be updated
in the next few weeks.

Please let me know if you have any question.

Best,

Sida

**Comment by Chris-Aitken** [comment]
Hi Sida,

Thank you for responding so quickly! I modified `hdCBPS.fit` in line with your suggestions and rebuilt the package. It seems to be working perfectly now. Just to confirm, is the expected formula syntax `treatment_var ~ x_1 + x_2 + ... + x_d`, as in the `CBPS` LaLonde-based example?

Best,

Chris

**Comment by psdsam** [comment]
Hi Chris,

Yes, the syntax is the same as standard CBPS package as you wrote down.

Best,

Sida

**Comment by kosukeimai** [comment]
@psdsam Can you go ahead and make the change to the code?

**Comment by psdsam** [comment]
Yang and I are working on a modified method. We can update those all at
once? Or I can do a quick pull request and fix this first?

Let me know which one you prefer?

Thank you,

Best,

Sida

**Comment by kosukeimai** [comment]
I think you can do a quick fix so that the problem does not occur again for the mean time.

**Comment by psdsam** [comment]
just did the change
